baseurl             = "https://chroju.github.io"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "ja"
hasCJKLanguage      = true
enableEmoji         = true
layoutdir           = "layouts"
publishdir          = "public"
theme               = "noteworthy"
author              = "chroju"
title               = "the world as code"
pygmentsCodefences  = true
pygmentsStyle       = "solarized-dark"
pygmentsOptions     = "linenos=inline"
googleAnalytics     = "UA-6765151-2"

[authoer]
name = "chroju"

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss"
baseName = "atom"

[permalinks]
blog = "/blog/:year/:month/:day/:filename/"

[[menu.main]]
name                   = "Archive"
weight                 = -120
identifier             = "archives"
url                    = "/archives"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about"

[params]
i18n_flags             = false                         # whether to display small country flags for available translations
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 JST"
# description            = "write code to automate everything."
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
github                 = "chroju"
twitter                = "chroju"
lang                   = "ja"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string


[markup.goldmark.renderer]
  unsafe = true
